artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
  local_data_file : artifacts/data_ingestion/summarizer-data.zip  
  unzip_dir: artifacts/data_ingestion/unzip_data


data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
